language: generic
sudo: required
services:
  - docker

before_install:
  # dockerid/name_of_your_image
  - docker build -t fikircik/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fikircik/multi-docker npm test

after_success:
  - docker build -t fikircik/multi-docker-client ./client
  - docker build -t fikircik/multi-docker-nginx ./nginx
  - docker build -t fikircik/multi-docker-server ./server
  - docker build -t fikircik/multi-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push it to hub.docker
  - docker push fikircik/multi-docker-client
  - docker push fikircik/multi-docker-nginx
  - docker push fikircik/multi-docker-server
  - docker push fikircik/multi-docker-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
